require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const axios = require('axios');

// Import Models
const User = require('./models/User');
const Product = require('./models/Product');
const Order = require('./models/Order');

const app = express();
const PORT = process.env.PORT || 5000;
const NLP_SERVICE_URL = process.env.NLP_SERVICE_URL || 'http://localhost:8000/translate';
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/luminadb';

// Middleware
app.use(cors());
app.use(express.json());

// Add a test route to verify server is running
app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', message: 'LuminaDB Backend running' });
});

// Main query route
app.post('/api/query', async (req, res) => {
  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required in request body.' });
  }

  try {
    // 1. Forward prompt to NLP Service for MQL Translation
    const nlpResponse = await axios.post(NLP_SERVICE_URL, { prompt });
    const mql = nlpResponse.data;

    if (!mql || !mql.collection || !mql.action) {
      return res.status(500).json({ error: 'Invalid MQL generated by NLP service.', rawResponse: mql });
    }

    // 2. Map collection name to actual Mongoose model
    let Model;
    switch (mql.collection.toLowerCase()) {
      case 'user':
        Model = User;
        break;
      case 'product':
        Model = Product;
        break;
      case 'order':
        Model = Order;
        break;
      default:
        return res.status(400).json({ error: `Collection '${mql.collection}' is not supported.` });
    }

    // 3. Execute the query
    let results;
    const query = mql.query || {};
    
    if (mql.action === 'find') {
       let tempQuery = Model.find(query);
       
       if (mql.sort) {
         tempQuery = tempQuery.sort(mql.sort);
       }
       if (mql.limit) {
         tempQuery = tempQuery.limit(mql.limit);
       }
       
       results = await tempQuery.exec();
    } else if (mql.action === 'aggregate' && Array.isArray(mql.pipeline)) {
       results = await Model.aggregate(mql.pipeline).exec();
    } else {
       return res.status(400).json({ error: `Action '${mql.action}' is not supported. Use 'find' or 'aggregate'.` });
    }

    // 4. Return results and the raw MQL used
    res.json({
      mql,
      results
    });

  } catch (error) {
    console.error('Error processing query:', error.message);
    if (error.response && error.response.data) {
        return res.status(500).json({ error: 'Error from NLP Service', details: error.response.data });
    }
    res.status(500).json({ error: 'Internal server error while processing query.' });
  }
});

// Connect to MongoDB and start the server
mongoose.connect(MONGODB_URI)
  .then(() => {
    console.log(`Connected to MongoDB: ${MONGODB_URI}`);
    app.listen(PORT, () => {
      console.log(`LuminaDB Backend orchestrator listening on port ${PORT}`);
    });
  })
  .catch((err) => {
    console.error('Failed to connect to MongoDB', err);
    process.exit(1);
  });
